version: '3'

services:
  distro:
    image: alpine
    restart: always
    container_name: Custom_alpine
    entrypoint: tail -f /dev/null
  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    volumes:
      - ../dump:/tmp/
